#!/bin/sh

FLAGS=""
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

set -e
set -x

#
# this code is optimized for cloning a single
# branch if the target directory is empty and
# will use the tag as the branch name.
#
#
git clone ${FLAGS} --branch ${DRONE_TAG} --single-branch \
  ${DRONE_REMOTE_URL} ${DRONE_WORKSPACE}
